# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: monitoring
#   labels:
#     monitoring: prometheus
# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: ingress-nginx
#   labels:
#     name: ingress-nginx
---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: {{ .Values.webapp.namespace | default "chat "}}
#   labels:
#     name: {{ .Values.webapp.namespace | default "chat "}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  {{- include "metadata" . | nindent 2 }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.webapp.name | default "chat" }}
  template:
    metadata:
      labels:
        app: {{ .Values.webapp.name | default "chat" }}
    spec:
      containers:
      - name: {{ .Values.webapp.name | default "chat "}}
        image: "{{ .Values.webapp.repo | default "dirt1992 "}}/{{ .Values.webapp.image | default "shitchat" }}:{{ .Values.webapp.tag | default "v0.2" }}"
        imagePullPolicy: {{ .Values.webapp.pullPolicy | default "IfNotPresent" }}
        ports:
        - containerPort: {{ .Values.contPort | default 3000 }}
      {{- if .Values.affinity }}
      affinity:
        {{- if .Values.affinity.antiAffinity }}
        podAntiAffinity:
          {{ if eq .Values.affinity.antiAffinity.requiredignored false }}
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - {{ $.Values.webapp.name | default "chat" }}
              topologyKey: "kubernetes.io/hostname"
          {{ end }}
          {{- if eq .Values.affinity.antiAffinity.preferredignored true -}}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - {{ $.Values.webapp.name | default "chat" }}
              topologyKey: "kubernetes.io/hostname"
          {{- end -}}
        {{- end }}
      {{- end }}
      # imagePullSecrets:
      # - name: {{ .Values.imagePullSecretsName | default "regcred" }} # shouldn't be here but it's a private repo
---
apiVersion: v1
kind: Service
metadata:
  {{- include "metadata" . | nindent 2 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: {{ .Values.webapp.name | default "chat" }}
  ports:
  - port: {{ .Values.service.port | default 3000 }}
    targetPort: {{ .Values.contPort | default 3000 }} 
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- include "metadata" . | nindent 2 }}
  labels:
    name: {{ .Values.webapp.name | default "chat" }}
spec:
  ingressClassName: nginx
  rules:
  - host: madsuchat.com
    http:
      paths:
      - path: / 
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.webapp.name | default "chat" }}
            port:
              number: {{ .Values.service.port | default 3000 }} 

