---
# Source: kube-prometheus-stack/charts/grafana/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    helm.sh/chart: grafana-6.57.4
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: kps
    app.kubernetes.io/version: "9.5.5"
    app.kubernetes.io/managed-by: Helm
  name: kps-grafana
  namespace: monitoring
