---
# Source: kube-prometheus-stack/templates/prometheus/prometheus.yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: kps-kube-prometheus-stack-prometheus
  namespace: monitoring
  labels:
    app: kube-prometheus-stack-prometheus
    
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: kps
    app.kubernetes.io/version: "47.4.0"
    app.kubernetes.io/part-of: kube-prometheus-stack
    chart: kube-prometheus-stack-47.4.0
    release: "kps"
    heritage: "Helm"
spec:
  alerting:
    alertmanagers:
      - namespace: monitoring
        name: kps-kube-prometheus-stack-alertmanager
        port: http-web
        pathPrefix: "/"
        apiVersion: v2
  image: "quay.io/prometheus/prometheus:v2.45.0"
  version: v2.45.0
  externalUrl: http://kps-kube-prometheus-stack-prometheus.monitoring:9090
  paused: false
  replicas: 1
  shards: 1
  logLevel:  info
  logFormat:  logfmt
  listenLocal: false
  enableAdminAPI: false
  retention: "10d"
  tsdb:
    outOfOrderTimeWindow: 0s
  walCompression: true
  routePrefix: "/"
  serviceAccountName: kps-kube-prometheus-stack-prometheus
  serviceMonitorSelector:
    matchLabels:
      prometheus: prom-mads

  serviceMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      release: "kps"

  podMonitorNamespaceSelector: {}
  probeSelector:
    matchLabels:
      release: "kps"

  probeNamespaceSelector: {}
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      release: "kps"

  scrapeConfigSelector:
    matchLabels:
      release: "kps"

  scrapeConfigNamespaceSelector: {}
  portName: http-web
  hostNetwork: false
